server:
  port: 9191
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


    eureka:
      client:
        register-with-eureka: true
        fetchRegistry: true
    service-url:
      defaultZone: http:localhost:8761/eureka/
      instance:
        hostname: localhost